AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create an S3 bucket'

Resources:
  ECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: forum-app

Outputs:
  RepositoryURL:
    Description: The URL of the created ECR repository 1
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}"