name: Deploy AWS Stack

on:
  push:
    branches:
      - master
    paths:
      - "ENV/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your desired AWS region
    
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Deploy CloudFormation stack
      run: |
        STACK_NAME="forum-stack" # Replace with your desired stack name
        TEMPLATE_FILE="ENV/forum-stack.yaml" # Replace with the path to your CloudFormation template

        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file $TEMPLATE_FILE \
          --capabilities CAPABILITY_NAMED_IAM # Modify the `--capabilities` flag as needed
